// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjB6xu63hsFDobnR5CMHceeDpSjguefOo',
    appId: '1:114942155205:android:7a8bdb25ddd31efa9393ac',
    messagingSenderId: '114942155205',
    projectId: 'weatherapp-2a5b4',
  );

  static const FirebaseOptions ios = FirebaseOptions(
      apiKey: 'AIzaSyBjB6xu63hsFDobnR5CMHceeDpSjguefOo',
      appId: '1:114942155205:ios:8f193936737c6ae99393ac',
      messagingSenderId: '114942155205',
      projectId: 'weatherapp-2a5b4',
      iosBundleId: 'com.example.weatherApp',
      storageBucket: 'weatherapp-2a5b4.appspot.com');
}
